// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBxmVPQWUmjVeD0K8at6TpddwX4DlYyu0',
    appId: '1:174126837732:web:7d64b27d37d536a58fa1f1',
    messagingSenderId: '174126837732',
    projectId: 'movie-night-f2377',
    authDomain: 'movie-night-f2377.firebaseapp.com',
    storageBucket: 'movie-night-f2377.firebasestorage.app',
    measurementId: 'G-GCS35QLL6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZfAArav_F2zfm7ZZMXTXR41neA8gYNCE',
    appId: '1:174126837732:android:bfca378626ef81c68fa1f1',
    messagingSenderId: '174126837732',
    projectId: 'movie-night-f2377',
    storageBucket: 'movie-night-f2377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtzPYVHuW31d50mWEeSTXAdXDqY7Vk9bI',
    appId: '1:174126837732:ios:2a5e9e8554629e5f8fa1f1',
    messagingSenderId: '174126837732',
    projectId: 'movie-night-f2377',
    storageBucket: 'movie-night-f2377.firebasestorage.app',
    iosClientId: '174126837732-bra9rv1p1r1ppqttbj2cbpk5kio0gj0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieNight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtzPYVHuW31d50mWEeSTXAdXDqY7Vk9bI',
    appId: '1:174126837732:ios:2a5e9e8554629e5f8fa1f1',
    messagingSenderId: '174126837732',
    projectId: 'movie-night-f2377',
    storageBucket: 'movie-night-f2377.firebasestorage.app',
    iosClientId: '174126837732-bra9rv1p1r1ppqttbj2cbpk5kio0gj0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieNight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBxmVPQWUmjVeD0K8at6TpddwX4DlYyu0',
    appId: '1:174126837732:web:12dfcb22b2f0e9e48fa1f1',
    messagingSenderId: '174126837732',
    projectId: 'movie-night-f2377',
    authDomain: 'movie-night-f2377.firebaseapp.com',
    storageBucket: 'movie-night-f2377.firebasestorage.app',
    measurementId: 'G-ZJGECV7010',
  );
}
